### PR TITLE
fix: index.d.ts extends IMountOptions by AuthenticateOptions.

### PR DESCRIPTION
**Pull request by lightrabbit**
##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message follows commit guidelines

##### Description of change

完善了声明文件，`passport.mount` 中的 `options` 参数会传递给 `passport.authenticate`，所以`passport.mount`  的 `options` 参数也应该拥有 `passport.authenticate` 的 `options` 参数中的选项。

### CODE REVIEW

**Comment by zzh8829** [comment]
bump, this fixes my issue with mounting parameters

**Review by hyj1991 — APPROVED** [review]
+1

**Comment by atian25** [comment]
ci 挂了？

**Comment by lightrabbit** [comment]
@atian25 好像是在ci的环境中，微博api的key和secret没有作为环境变量传递到配置里面

**Review by whxaxes — APPROVED** [review]

**Comment by whxaxes** [comment]
2.1.1

**Pull request merged**
